### ISSUE TITLE
ПР4 (ломаная линия)

### ISSUE THREAD

**Issue by drxaos** [shadowzer/java#1]
1. Вместо isEquals лучше переопределить стандартную equals.
2. Код

```
        double x = p.getCoordinates()[0];
        double y = p.getCoordinates()[1];
```

создает два массива с координатами (проблем с производительностью это не создаст, но выглядит как небрежность). Метод getCoordinates вообще не имеет смысла, так как класс Point сам по себе является структурой, хранящей эти координаты и перекладывать их в другую структуру незачем.
А в данной конкретной программе метод getCoordinates еще и используется только внутри класса Point, хотя ничто не мешает ему обращаться к своим полям напрямую.
3. В методе isContinue также использование массива вместо двух переменных не приносит пользы, а только затрудняет чтение кода.

**Comment by shadowzer** [comment]
fixed.
